### ISSUE TITLE
这是阿里的员工写的吗？demo都跑不起来，就这样？

### ISSUE THREAD

**Issue by lilei10101010** [aliyun/alibabacloud-php-sdk#10]
这是阿里的员工写的吗？demo都跑不起来，就这样？
https://github.com/aliyun/alibabacloud-php-sdk/blob/master/docs/0-Examples-CN.md#%E5%BF%AB%E9%80%9F%E4%BD%BF%E7%94%A8

**Comment by gtspoon** [comment]
感觉越来越烂了

**Comment by TsinghuaDream** [comment]
已修复 感谢反馈
