### ISSUE TITLE
项目的文档是无效的别看了，使用文档应参考OpenAPI 开发者门户

### ISSUE THREAD

**Issue by lty628** [aliyun/alibabacloud-php-sdk#12]
[OpenAPI 开发者门户](https://next.api.aliyun.com/product/Push?spm=a2c4g.11186623.0.0.31355d7aoSCKL7)

**Comment by aboutZZ** [comment]
文档管理混乱，我翻看官网文档，已经看到让你用三个版本SDK
```
alibabacloud/live-20161101

alibabacloud/live

alibabacloud/darabonba-openapi
```
到底哪个是新版，哪个不维护了，混乱的一批。

**Comment by lty628** [comment]
https://next.api.aliyun.com/api-tools/sdk/live?version=2016-11-01&language=java-async-tea

**Comment by lty628** [comment]
@aboutZZ  第一个
