### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by congyukun** [aliyun/alibabacloud-php-sdk#21]
g_vendor/vendor/alibabacloud/schedulerx2-20190430/src/Schedulerx2.php   
createJobWithOptions  **WithOptions  多个 namespace写错了 写成了namespace_
src/Schedulerx2.php 388行 很多

**Comment by TsinghuaDream** [comment]
这是因为namespace是PHP的关键字，业务字段存在namespace的时候做的兼容。
