### ISSUE TITLE
短信sdk dysmsapi-20170525的报错问题，用的示例

### ISSUE THREAD

**Issue by asyncpjax** [aliyun/alibabacloud-php-sdk#22]
`ErrorException: Undefined property: AlibabaCloud\Credentials\Credential\Config::$endpointType in D:\phpstudy_pro\WWW\2023\tiaojie-php\vendor\alibabacloud\darabonba-openapi\src\OpenApiClient.php:118`

**Comment by TsinghuaDream** [comment]
把次级依赖版本都升级到最新呢
alibabacloud/darabonba-openapi 0.2.11
alibabacloud/credentials 1.1.5

**Comment by ufly-site** [comment]
use Darabonba\OpenApi\Models\Config;
Config 引错包了
