### ISSUE TITLE
无法直接使用composer安装

### ISSUE THREAD

**Issue by yanyixin0612** [aliyun/alibabacloud-php-sdk#23]
执行composer require alibabacloud/dingtalk之后报错信息如下:
`  Problem 1
    - Root composer.json requires alibabacloud/dingtalk ^2.0 -> satisfiable by alibabacloud/dingtalk[2.0.0, 2.0.10, 2.0.11, 2.0.12].
    - alibabacloud/dingtalk[2.0.0, ..., 2.0.12] require alibabacloud/gateway-dingtalk ^1.0.2 -> found alibabacloud/gateway-dingtalk[dev-master, 1.0.0, 1.0.1] but it does not match the constraint.`
意思是要求alibabacloud/gateway-dingtalk ^1.0.2, 但是只能找到 ^1.0.1?

**Comment by yanyixin1993** [comment]
安装1.5.65版本的倒是没问题

**Comment by TsinghuaDream** [comment]
应该是镜像站的同步时间问题，最新版本是直接发布到中央仓库的，未来可以配置中央仓库直接拉取。composer config -g repo.packagist composer https://repo.packagist.org/
