### ISSUE TITLE
php8.2动态属性 Deprecated: Creation of dynamic property   

### ISSUE THREAD

**Issue by liiy-liiy** [aliyun/alibabacloud-php-sdk#25]
使用 alibabacloud/dytnsapi-20200217  这个包的时候，
namespace AlibabaCloud\Tea;
class Model
{
    public function __construct($config = [])
    {
        if (!empty($config)) {
            foreach ($config as $k => $v) {
                $this->{$k} = $v;       //这里报动态属性的异常
            }
        }
    }
}

**Comment by TsinghuaDream** [comment]
8.2.3没遇到这个报错的，能发下具体的报错信息吗？

**Comment by 18827676454** [comment]
我也碰到这个问题了...  好像并不是警告类型
