### ISSUE TITLE
返回的字段文档与实际不一致，实际的首字母是小写

### ISSUE THREAD

**Issue by qqingdou** [aliyun/alibabacloud-php-sdk#3]
项目：alibabacloud/dysmsapi-20170525
文档：
{
    "Message": "OK",
    "RequestId": "F655A8D5-B967-440B-8683-DAD6FF8DE990",
    "Code": "OK",
    "BizId": "900619746936498440^0"
}
实际：
{
  "message": "OK",
  "requestId": "7935D64D-0C90-4D92-97A7-9CC40D441BD8",
  "code": "OK",
  "bizId": "344116320882057674"
}

**Comment by lty628** [comment]
代码里做了映射，阿里云那边是大写，但是代码里是小写，因为sdk里做了一次转换
