### ISSUE TITLE
包版本冲突

### ISSUE THREAD

**Issue by williamqian** [aliyun/alibabacloud-php-sdk#7]
![image](https://user-images.githubusercontent.com/19399075/143668645-fb41bfe3-1f98-4fca-801c-3d05e7ec1d47.png)

**Comment by imvkmark** [comment]
没有人解决这个问题

**Comment by TsinghuaDream** [comment]
alibabacloud/oss-20190517 1.0.5已无此问题，不过门户的oss SDK还在内部优化，建议先使用oss自研的PHP SDK
https://help.aliyun.com/zh/oss/developer-reference/php-1/?spm=a2c4g.11174283.0.0.7ca5de538vxWxv
