### ISSUE TITLE
文档中的示在SDK中找不到

### ISSUE THREAD

**Issue by zhaoxl** [aliyun/alibabacloud-php-sdk#8]
通过免登码获取用户信息接口文档中  相关的类在SDK中没有找到，怎么办？
SDK安装命令：
composer require alibabacloud/dingtalk
PHP版本示例：
https://open-dev.dingtalk.com/apiExplorer?spm=ding_open_doc.document.0.0.750877a2hQrUYP#/?devType=org&api=dingtalk.oapi.v2.user.getuserinfo

**Comment by TsinghuaDream** [comment]
这个接口暂时还是旧版SDK的，需要安装钉钉旧版SDK
![image](https://github.com/aliyun/alibabacloud-php-sdk/assets/43798276/4d5913f5-a53b-4bec-84d2-bb608eee0782)
